language: python
python:
  - 3.6
before_install:
  # install miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:

  # We just set up a conda environment with the right Python version. This
  # should not need changing.

  - conda env create -f environment.yml -n test
  - source activate test

script:
  - coverage run -m unittest discover

after_success:
  - coveralls
