language: python
python:
  - 3.8

cache: 
  - pip: true
  - directories:
    - $HOME/.cache/pypoetry

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - poetry run coverage run -m unittest discover

after_success:
  - poetry run coveralls


